### ISSUE TITLE
Job Boards We Like

### ISSUE THREAD

**Issue by vlucas** [techlahoma/project_job_board#1]
* https://authenticjobs.com/ - Because it is very simple - a few simple categories, search, and no on-site application process - it's just a link to the job somewhere else (or an email)

**Comment by vlucas** [comment]
Paging @matthewreily and @lucaswatson

**Comment by seejessicacode** [comment]
Job board will be done soon, can we close this issue?

**Comment by vlucas** [comment]
Yes.
