### ISSUE TITLE
Why two repos?

### ISSUE THREAD

**Issue by rhoegg** [techlahoma/project_job_board#2]
I see we have this and http://github.com/techahoma/jobboard, is that intentional?

**Comment by the-simian** [comment]
i'm getting a 404 on that other one, currently.

**Comment by seejessicacode** [comment]
what about this repo? https://github.com/techlahoma/jobboard

Looks like @rhoegg typo'd Techlahoma in his url.

**Comment by vlucas** [comment]
I will close this one. This is not needed anymore.
